[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
phantom = { path = "../../crates/engine" }
camera = { path = "../../crates/camera" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
